### ISSUE TITLE
Error when running yo app-website

### ISSUE THREAD

**Issue by jerry42** [anvilabs/generator-app-website#1]
Hello,
I've just installed your Yo generator and I'm getting the following error when running "yo app-website"

const generator = require('yeoman-generator');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.defineProperty.get [as app-website:app](/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:21)

Tried with a sudo but it changes nothing. 

Running on OSX

**Comment by yenbekbay** [comment]
@jerry42 You are apparently using an outdated version of node. Try updating node by running:

``` bash
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by jerry42** [comment]
My bad ! Thanks for the quick reply.
